config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get '/portfolio' => 'pages#portfolio'

  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def portfolio
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="nav">
        <ul class="pull-left">
          <li><%= link_to 'Welcome', root_path %></li>
          <li><%= link_to 'Portfolio', portfolio_path %></li>
          <li><a href="https://kraftwexpress.wordpress.com/">Blog</a></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path %></li>
        </ul>

        <ul class="pull-right">
          <li>Chen Yang</li>
        </ul>
      </div>
    </div>
  </div>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron about">
        <div class="container">

        </div>
      </div>

      <div class="container">
        <h2>About Chen Yang</h2>
        <p>A little about my background: I am a software product development manager who is super passionate about technology. I started my current role about two years ago fresh out of grad school, and during this job I have had the opportunity to learn about many aspects of software development process. What I enjoy the most about being a product manager is I get to be the bridge between our development team and business team, and in the center of how the whole product come together.

On weekends when I’m not learning coding, I enjoy cycling, kayaking, cooking, and great movies. I currently live in Austin, TX.</p>
      </div>
</div>

app/views/pages/contact.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <img src="https://upload.wikimedia.org/wikipedia/commons/f/f9/Linkedin_Shiny_Icon.svg" alt="linkedin thumbnail">
        <div class="caption">
          <h3>LinkedIn</h3>
          <p><a href="https://www.linkedin.com/pub/chen-yang/104/52a/b26" class="btn btn-primary" role="button">LinkedIn</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <img src="https://assets-cdn.github.com/images/modules/logos_page/Octocat.png" alt="Github logo">
        <div class="caption">
          <h3>GitHub</h3>
          <p><a href="https://github.com/yangc5" class="btn btn-primary" role="button">GitHub</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/WordPress_blue_logo.svg/2000px-WordPress_blue_logo.svg.png" alt="wordpress logo">
        <div class="caption">
          <h3>WordPress</h3>
          <p><a href="https://kraftwexpress.wordpress.com" class="btn btn-primary" role="button">View my blogs</a></p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/portfolio.html.erb
<div class="main">
  <div class="owl-carousel">

		<div class="thumbnail"><img src="https://res.cloudinary.com/dsw8fvr45/image/upload/v1447635813/tic_tac_toe_udwevv.png">My slide</div>
		<div class="thumbnail"><img src="https://res.cloudinary.com/dsw8fvr45/image/upload/v1447635809/people_cards_htysqs.png">Another slide</div>
		<div class="thumbnail"><img src="https://res.cloudinary.com/dsw8fvr45/image/upload/v1447635803/towers_isa3wk.png">My last slide</div>

</div>
</div>

app/views/pages/welcome.html.erb
<div class="jumbotron welcome">
  <div class="container">
    <h2 class="right">Hello. My name is <span class="highlight">Chen Yang</span> and I have creative ideas and build websites</h2>
    <%= link_to 'View My Work', portfolio_path, class: "btn right" %>
  </div>
</div>

<div class="footer">
  <div class="container">
    <ul class="social_media">
      <li><a class="github" href="https://github.com/yangc5"></a></li>
      <li><a class="linkedin" href="https://www.linkedin.com/pub/chen-yang/104/52a/b26"></a></li>
    </ul>
    <p>@Chen Yang 2015</p>
    <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>             is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>
  </div>
</div>